

CREATE SCHEMA IF NOT EXISTS securecapita;

SET NAMES = 'UTF8MB4';
SET TIME_ZONE = 'America/Lima';

USE securecapita;

DROP TABLE IF EXISTS Users;

CREATE TABLE Users(
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    email VARCHAR(70) NOT NULL,
    password VARCHAR(50) DEFAULT NULL,
    address VARCHAR(100) DEFAULT NULL,
    phone VARCHAR(30) DEFAULT NULL,
    title VARCHAR(50) DEFAULT NULL,
    bio VARCHAR(255) DEFAULT NULL

)